# Generated by Django 4.1.2 on 2022-10-13 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='creation_date',
            new_name='registration_date',
        ),
    ]
